const baseWidth = 'base-width';
const midWidth = 'mid-width';
const largeWidth = 'large-width';
const alternative = 'alternative';
const functional = 'functional';
const letter = 'letter';

export const keys = [
  {
    text: {en: '`', ru: 'ё'},
    altText: {en: '~', ru: 'ё'},
    width: baseWidth,
    type: alternative,
    code: 'Backquote',
    end: false,
  },
  {
    text: {en: '1', ru: '1'},
    altText: {en: '!', ru: '!'},
    width: baseWidth,
    type: alternative,
    code: 'Digit1',
    end: false,
  },
  {
    text: {en: '2', ru: '2'},
    altText: {en: '@', ru: '"'},
    width: baseWidth,
    type: alternative,
    code: 'Digit2',
    end: false,
  },
  {
    text: {en: '3', ru: '3'},
    altText: {en: '#', ru: '№'},
    width: baseWidth,
    type: alternative,
    code: 'Digit3',
    end: false,
  },
  {
    text: {en: '4', ru: '4'},
    altText: {en: '$', ru: ';'},
    width: baseWidth,
    type: alternative,
    code: 'Digit4',
    end: false,
  },
  {
    text: {en: '5', ru: '5'},
    altText: {en: '%', ru: '%'},
    width: baseWidth,
    type: alternative,
    code: 'Digit5',
    end: false,
  },
  {
    text: {en: '6', ru: '6'},
    altText: {en: '^', ru: ':'},
    width: baseWidth,
    type: alternative,
    code: 'Digit6',
    end: false,
  },
  {
    text: {en: '7', ru: '7'},
    altText: {en: '&', ru: '?'},
    width: baseWidth,
    type: alternative,
    code: 'Digit7',
    end: false,
  },
  {
    text: {en: '8', ru: '8'},
    altText: {en: '*', ru: '*'},
    width: baseWidth,
    type: alternative,
    code: 'Digit8',
    end: false,
  },
  {
    text: {en: '9', ru: '9'},
    altText: {en: '(', ru: '('},
    width: baseWidth,
    type: alternative,
    code: 'Digit9',
    end: false,
  },
  {
    text: {en: '0', ru: '0'},
    altText: {en: ')', ru: ')'},
    width: baseWidth,
    type: alternative,
    code: 'Digit0',
    end: false,
  },
  {
    text: {en: '-', ru: '-'},
    altText: {en: '_', ru: '_'},
    width: baseWidth,
    type: alternative,
    code: 'Minus',
    end: false,
  },
  {
    text: {en: '=', ru: '='},
    altText: {en: '+', ru: '+'},
    width: baseWidth,
    type: alternative,
    code: 'Equal',
    end: false,
  },
  {
    text: {en: 'Backspace', ru: 'Backspace'},
    altText: {en: 'Backspace', ru: 'Backspace'},
    width: largeWidth,
    type: functional,
    code: 'Backspace',
    end: true,
  },
  {
    text: {en: 'Tab', ru: 'Tab'},
    altText: {en: 'Tab', ru: 'Tab'},
    width: midWidth,
    type: functional,
    code: 'Tab',
    end: false,
  },
  {
    text: {en: 'q', ru: 'й'},
    altText: {en: 'q', ru: 'й'},
    width: baseWidth,
    type: letter,
    code: 'KeyQ',
    end: false,
  },
  {
    text: {en: 'w', ru: 'ц'},
    altText: {en: 'w', ru: 'ц'},
    width: baseWidth,
    type: letter,
    code: 'KeyW',
    end: false,
  },
  {
    text: {en: 'e', ru: 'у'},
    altText: {en: 'e', ru: 'у'},
    width: baseWidth,
    type: letter,
    code: 'KeyE',
    end: false,
  },
  {
    text: {en: 'r', ru: 'к'},
    altText: {en: 'r', ru: 'к'},
    width: baseWidth,
    type: letter,
    code: 'KeyR',
    end: false,
  },
  {
    text: {en: 't', ru: 'е'},
    altText: {en: 't', ru: 'е'},
    width: baseWidth,
    type: letter,
    code: 'KeyT',
    end: false,
  },
  {
    text: {en: 'y', ru: 'н'},
    altText: {en: 'y', ru: 'н'},
    width: baseWidth,
    type: letter,
    code: 'KeyY',
    end: false,
  },
  {
    text: {en: 'u', ru: 'г'},
    altText: {en: 'u', ru: 'г'},
    width: baseWidth,
    type: letter,
    code: 'KeyU',
    end: false,
  },
  {
    text: {en: 'i', ru: 'ш'},
    altText: {en: 'i', ru: 'ш'},
    width: baseWidth,
    type: letter,
    code: 'KeyI',
    end: false,
  },
  {
    text: {en: 'o', ru: 'щ'},
    altText: {en: 'o', ru: 'щ'},
    width: baseWidth,
    type: letter,
    code: 'KeyO',
    end: false,
  },
  {
    text: {en: 'p', ru: 'з'},
    altText: {en: 'p', ru: 'з'},
    width: baseWidth,
    type: letter,
    code: 'KeyP',
    end: false,
  },
  {
    text: {en: '[', ru: 'х'},
    altText: {en: '{', ru: 'х'},
    width: baseWidth,
    type: alternative,
    code: 'BracketLeft',
    end: false,
  },
  {
    text: {en: ']', ru: 'ъ'},
    altText: {en: '}', ru: 'ъ'},
    width: baseWidth,
    type: alternative,
    code: 'BracketRight',
    end: false,
  },
  {
    text: {en: '\\', ru: '\\'},
    altText: {en: '|', ru: '/'},
    width: baseWidth,
    type: alternative,
    code: 'Backslash',
    end: false,
  },
  {
    text: {en: 'DEL', ru: 'DEL'},
    altText: {en: 'DEL', ru: 'DEL'},
    width: midWidth,
    type: functional,
    code: 'Delete',
    end: true,
  },
  {
    text: {en: 'Caps Lock', ru: 'Caps Lock'},
    altText: {en: 'Caps Lock', ru: 'Caps Lock'},
    width: midWidth,
    type: functional,
    code: 'CapsLock',
    end: false,
  },
  {
    text: {en: 'a', ru: 'ф'},
    altText: {en: 'a', ru: 'ф'},
    width: baseWidth,
    type: letter,
    code: 'KeyA',
    end: false,
  },
  {
    text: {en: 's', ru: 'ы'},
    altText: {en: 's', ru: 'ы'},
    width: baseWidth,
    type: letter,
    code: 'KeyS',
    end: false,
  },
  {
    text: {en: 'd', ru: 'в'},
    altText: {en: 'd', ru: 'в'},
    width: baseWidth,
    type: letter,
    code: 'KeyD',
    end: false,
  },
  {
    text: {en: 'f', ru: 'а'},
    altText: {en: 'f', ru: 'а'},
    width: baseWidth,
    type: letter,
    code: 'KeyF',
    end: false,
  },
  {
    text: {en: 'g', ru: 'п'},
    altText: {en: 'g', ru: 'п'},
    width: baseWidth,
    type: letter,
    code: 'KeyG',
    end: false,
  },
  {
    text: {en: 'h', ru: 'р'},
    altText: {en: 'h', ru: 'р'},
    width: baseWidth,
    type: letter,
    code: 'KeyH',
    end: false,
  },
  {
    text: {en: 'j', ru: 'о'},
    altText: {en: 'j', ru: 'о'},
    width: baseWidth,
    type: letter,
    code: 'KeyJ',
    end: false,
  },
  {
    text: {en: 'k', ru: 'л'},
    altText: {en: 'k', ru: 'л'},
    width: baseWidth,
    type: letter,
    code: 'KeyK',
    end: false,
  },
  {
    text: {en: 'l', ru: 'д'},
    altText: {en: 'l', ru: 'д'},
    width: baseWidth,
    type: letter,
    code: 'KeyL',
    end: false,
  },
  {
    text: {en: ';', ru: 'ж'},
    altText: {en: ':', ru: 'ж'},
    width: baseWidth,
    type: alternative,
    code: 'Semicolon',
    end: false,
  },
  {
    text: {en: `'`, ru: 'э'},
    altText: {en: '"', ru: 'э'},
    width: baseWidth,
    type: alternative,
    code: 'Quote',
    end: false,
  },
  {
    text: {en: 'ENTER', ru: 'ENTER'},
    altText: {en: 'ENTER', ru: 'ENTER'},
    width: largeWidth,
    type: functional,
    code: 'Enter',
    end: true,
  },
  {
    text: {en: 'Shift', ru: 'Shift'},
    altText: {en: 'Shift', ru: 'Shift'},
    width: largeWidth,
    type: functional,
    code: 'ShiftLeft',
    end: false,
  },
  {
    text: {en: 'z', ru: 'я'},
    altText: {en: 'z', ru: 'я'},
    width: baseWidth,
    type: letter,
    code: 'KeyZ',
    end: false,
  },
  {
    text: {en: 'x', ru: 'ч'},
    altText: {en: 'x', ru: 'ч'},
    width: baseWidth,
    type: letter,
    code: 'KeyX',
    end: false,
  },
  {
    text: {en: 'c', ru: 'с'},
    altText: {en: 'c', ru: 'с'},
    width: baseWidth,
    type: letter,
    code: 'KeyC',
    end: false,
  },
  {
    text: {en: 'v', ru: 'м'},
    altText: {en: 'v', ru: 'м'},
    width: baseWidth,
    type: letter,
    code: 'KeyV',
    end: false,
  },
  {
    text: {en: 'b', ru: 'и'},
    altText: {en: 'b', ru: 'и'},
    width: baseWidth,
    type: letter,
    code: 'KeyB',
    end: false,
  },
  {
    text: {en: 'n', ru: 'т'},
    altText: {en: 'n', ru: 'т'},
    width: baseWidth,
    type: letter,
    code: 'KeyN',
    end: false,
  },
  {
    text: {en: 'm', ru: 'ь'},
    altText: {en: 'm', ru: 'ь'},
    width: baseWidth,
    type: letter,
    code: 'KeyM',
    end: false,
  },
  {
    text: {en: ',', ru: 'б'},
    altText: {en: '<', ru: 'б'},
    width: baseWidth,
    type: alternative,
    code: 'Comma',
    end: false,
  },
  {
    text: {en: '.', ru: 'ю'},
    altText: {en: '>', ru: 'ю'},
    width: baseWidth,
    type: alternative,
    code: 'Period',
    end: false,
  },
  {
    text: {en: '/', ru: '.'},
    altText: {en: '?', ru: ','},
    width: baseWidth,
    type: alternative,
    code: 'Slash',
    end: false,
  },
  {
    text: {en: '&#8593;', ru: '&#8593;'},
    altText: {en: '&#8593;', ru: '&#8593;'},
    width: baseWidth,
    type: functional,
    code: 'ArrowUp',
    end: false,
  },
  {
    text: {en: 'Shift', ru: 'Shift'},
    altText: {en: 'Shift', ru: 'Shift'},
    width: largeWidth,
    type: functional,
    code: 'ShiftRight',
    end: true,
  },
  {
    text: {en: 'Ctrl', ru: 'Ctrl'},
    altText: {en: 'Ctrl', ru: 'Ctrl'},
    width: midWidth,
    type: functional,
    code: 'ControlLeft',
    end: false,
  },
  {
    text: {en: 'Win', ru: 'Win'},
    altText: {en: 'Win', ru: 'Win'},
    width: baseWidth,
    type: functional,
    code: 'OSLeft',
    end: false,
  },
  {
    text: {en: 'Alt', ru: 'Alt'},
    altText: {en: 'Alt', ru: 'Alt'},
    width: midWidth,
    type: functional,
    code: 'AltLeft',
    end: false,
  },
  {
    text: {en: ' ', ru: ' '},
    altText: {en: ' ', ru: ' '},
    width: 'space-width',
    type: letter,
    code: 'Space',
    end: false,
  },
  {
    text: {en: 'Alt', ru: 'Alt'},
    altText: {en: 'Alt', ru: 'Alt'},
    width: midWidth,
    type: functional,
    code: 'AltRight',
    end: false,
  },
  {
    text: {en: '&#8592;', ru: '&#8592;'},
    altText: {en: '&#8592;', ru: '&#8592;'},
    width: baseWidth,
    type: functional,
    code: 'ArrowLeft',
    end: false,
  },
  {
    text: {en: '&#8595;', ru: '&#8595;'},
    altText: {en: '&#8595;', ru: '&#8595;'},
    width: baseWidth,
    type: functional,
    code: 'ArrowDown',
    end: false,
  },
  {
    text: {en: '&#8594;', ru: '&#8594;'},
    altText: {en: '&#8594;', ru: '&#8594;'},
    width: baseWidth,
    type: functional,
    code: 'ArrowRight',
    end: false,
  },
  {
    text: {en: 'Ctrl', ru: 'Ctrl'},
    altText: {en: 'Ctrl', ru: 'Ctrl'},
    width: midWidth,
    type: functional,
    code: 'ControlRight',
    end: true,
  },
];
