export let objKeys = {
  backspaceKey: 'Backspace',
  tabKey: 'Tab',
  delKey: 'DEL',
  capsKey: 'Caps Lock',
  capsKeyCode: 'CapsLock',
  enterKey: 'ENTER',
  shiftKey: 'Shift',
  shiftLeftKey: 'ShiftLeft',
  shiftRightKey: 'ShiftRight',
  ctrlKey: 'Ctrl',
  winKey: 'Win',
  altKey: 'Alt',
  arrowUpKey: '&#8593;',
  arrowLeftKey: '&#8592;',
  arrowDownKey: '&#8595;',
  arrowRightKey: '&#8594;',
  arrowUp: 'ArrowUp',
  arrowLeft: 'ArrowLeft',
  arrowDown: 'ArrowDown',
  arrowRight: 'ArrowRight',
  controlLeftKey: 'ControlLeft',
  controlRightKey: 'ControlRight',
  alternative: 'alternative',
  functional: 'functional',
}
